### ISSUE TITLE
mapbox-upload-validate errors

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-swoop#11]
Seeing in master tests that used to pass but fail after restarting an old job:

```
mapbox-upload-validate --> 

waiting...

not ok 141 is valid

  ---

    operator: ok

    expected: true

    actual:   false

    at: fail (/Users/travis/build/mapbox/mapnik-swoop/node_modules/mapbox-upload-validate/index.js:9:48)

  ...

not ok 142 no message

  ---

    operator: notOk

    expected: false

    actual:   'Tileset does not exist'

    at: fail (/Users/travis/build/mapbox/mapnik-swoop/node_modules/mapbox-upload-validate/index.js:9:48)

  ...

# lib.invalid

waiting...



/Users/travis/build/mapbox/mapnik-swoop/node_modules/mapbox-upload-validate/test/shell.script.test.js:45

        if (err) throw err;

              

        ^

Error: Command failed: Tileset does not exist



    at ChildProcess.exithandler (child_process.js:658:15)

    at ChildProcess.emit (events.js:98:17)

    at maybeClose (child_process.js:766:16)

    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

```

**Comment by springmeyer** [comment]
Retarted a previously passing job at mapbox-upload-validate (https://travis-ci.org/mapbox/mapbox-upload-validate/jobs/109697960#L569) and it is also failing now. Seems something changed upstream in the test fixtures.

**Comment by springmeyer** [comment]
-> https://github.com/mapbox/mapbox-upload-validate/issues/55
